
skillMetadata:
  sections:
    - name: Options 
      fields:
        - name: home_assistant_host
          type: text
          label: Home assistant Host
          value: "localhost"
        - name: home_assistant_port
          type: text
          label: Home assistant Port
          value: "8123"
        - name: home_assistant_api_key
          type: text
          label: Home assistant Host
          value: ""
